name: Daily Run Scraping

on:
  schedule:
    # Run at midnight every day (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering for testing

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger scraping endpoint
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            ${{ secrets.NEXT_PUBLIC_APP_URL }}/api/cron/scrape
